@startuml
title Raspberry Pi - Arduino Communication Protocol

participant "Raspberry Pi" as pi
participant Arduino as arduino

==Reading Commands==
... Arduino will send full JSON data to Pi every half a second ...
arduino -> pi: { Full JSON data }

==Writing Commands==
pi -> arduino: %A (Start moving)
...Separate command...
pi -> arduino: %B (Stop moving)
...Separate command...
pi -> arduino: %Cx (Change speed, 1-3, 1 is slow and 3 is fast, numbers are in ASCII)
...Separate command...
pi -> arduino: %Dx (Rotate the camera using the following rotation data, rotation speed in radian / second)
...Separate command...
pi -> arduino: %Ex (Rotate the robot using the following rotation data, rotation speed in radian / second)

legend
* All commands are in the format ^[%|^][A-Z]([A-Za-z0-9.,-{}"' ]*[&])?$ for ease of implementation
* All characters that are sent in the messages are ASCII characters
* Some communication examples could be found within pi-arduino-protocol-example.txt
end legend
@enduml